version: '3'
services:
  app:
    container_name: simpleblog
    #image: "simpleblog:v1.2"
    build: .
    ports: 
      - 8083:8083 # Forward the exposed port 8083 on the container to port 8083 on the host machine
    restart: on-failure
    volumes:
      - api:/app/
    depends_on:
      - postgres # This service depends on postgres. Start that first.
    networks:
      - simpleblog

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - app.env
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - simpleblog

volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  simpleblog:
